name: Azure Static Web Apps CI/CD - Production

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy_job:
    name: Build and Deploy to Production
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Build And Deploy to Azure Static Web Apps
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_HAPPY_COAST_062E48310 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"                 # Root of your Angular project
          api_location: ""                  # Set if you have an API
          output_location: "dist/store/browser" # Path to built Angular output
